### ISSUE TITLE
CASF-2016 file missing tsv

### ISSUE THREAD

**Issue by AlaaBessadok** [SimonCrouzet/g-plip#1]
Dear authors, I tried to run your code with the existing dataset mentioned in the readme file, but I got this 
FileNotFoundError: [Errno 2] No such file or directory: 'data/CASF-2016/20230627_casf_human-proteins_idmapping.tsv' when executing python -m scripts.construct_pdbbind.py
I downloaded the CASF-2016 dataset twice and did not find the file inside the folder. Any recommendations, please?
Many thanks in advance!

**Comment by SimonCrouzet** [comment]
Hello @AlaaBessadok,

Thanks for your message and your interest!

It indeed seems we were missing a file, my apologies for that. I fixed the issue (commit 7bea48d), you may want to try again after pulling the changes.

Best,
